[package]
name = "fltkrs-richtext"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = "^1.4.9"
tokio = { version = "1.29.1", features = ["full"] }
fltk-flow = "0.2.1"
