[package]
name = "fltkrs-richtext"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#fltk = { version = "^1.4", features = ["fltk-bundled"] }
fltk = "^1.4"
#tokio = { version = "1.29.1", features = ["rt", "macros", "rt-multi-thread", "sync", "time"] }
tokio = { version = "1.29.1", features = ["full"] }
